version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: serverpod_saas
      POSTGRES_PASSWORD: "LiqOQvLWsBfPImh6p4m8Slh93mLvZFyp"
    volumes:
      - serverpod_saas_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "844WXBL2mnvkFRy0i2Gy99uaKwj5DN5t"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  serverpod_saas_data:
